/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedRawMaterialsRouteImport } from './routes/_authenticated/raw-materials'
import { Route as AuthenticatedRawMaterialStockRouteImport } from './routes/_authenticated/raw-material-stock'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedProductStockRouteImport } from './routes/_authenticated/product-stock'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomerGroupsRouteImport } from './routes/_authenticated/customer-groups'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedAiInsightsRouteImport } from './routes/_authenticated/ai-insights'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/accounting'
import { Route as AuthenticatedTransfersIndexRouteImport } from './routes/_authenticated/transfers.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedProductionIndexRouteImport } from './routes/_authenticated/production.index'
import { Route as ApiPublicSupabaseProxyRouteImport } from './routes/api/public/supabase-proxy'
import { Route as AuthenticatedTransfersNewRouteImport } from './routes/_authenticated/transfers.new'
import { Route as AuthenticatedSettingsShowroomsRouteImport } from './routes/_authenticated/settings.showrooms'
import { Route as AuthenticatedSettingsLandingRouteImport } from './routes/_authenticated/settings.landing'
import { Route as AuthenticatedSettingsAccessRouteImport } from './routes/_authenticated/settings.access'
import { Route as AuthenticatedSalesReturnRouteImport } from './routes/_authenticated/sales.return'
import { Route as AuthenticatedSalesPaymentsRouteImport } from './routes/_authenticated/sales.payments'
import { Route as AuthenticatedSalesListRouteImport } from './routes/_authenticated/sales.list'
import { Route as AuthenticatedSalesHistoryRouteImport } from './routes/_authenticated/sales.history'
import { Route as AuthenticatedReportsStockRouteImport } from './routes/_authenticated/reports.stock'
import { Route as AuthenticatedReportsSalesRouteImport } from './routes/_authenticated/reports.sales'
import { Route as AuthenticatedReportsPurchaseRouteImport } from './routes/_authenticated/reports.purchase'
import { Route as AuthenticatedReportsLedgersRouteImport } from './routes/_authenticated/reports.ledgers'
import { Route as AuthenticatedReportsExpensesRouteImport } from './routes/_authenticated/reports.expenses'
import { Route as AuthenticatedPurchasingReturnsRouteImport } from './routes/_authenticated/purchasing.returns'
import { Route as AuthenticatedPurchasingPaymentsRouteImport } from './routes/_authenticated/purchasing.payments'
import { Route as AuthenticatedPurchasingNewRouteImport } from './routes/_authenticated/purchasing.new'
import { Route as AuthenticatedPurchasingListRouteImport } from './routes/_authenticated/purchasing.list'
import { Route as AuthenticatedPurchasingCategoriesRouteImport } from './routes/_authenticated/purchasing.categories'
import { Route as AuthenticatedProductsUnitsRouteImport } from './routes/_authenticated/products.units'
import { Route as AuthenticatedProductsSellingPriceGroupsRouteImport } from './routes/_authenticated/products.selling-price-groups'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedProductsCategoriesRouteImport } from './routes/_authenticated/products.categories'
import { Route as AuthenticatedProductionWorkOrdersRouteImport } from './routes/_authenticated/production.work-orders'
import { Route as AuthenticatedProductionWastageRouteImport } from './routes/_authenticated/production.wastage'
import { Route as AuthenticatedProductionRepurposeRouteImport } from './routes/_authenticated/production.repurpose'
import { Route as AuthenticatedProductionRecipeCategoriesRouteImport } from './routes/_authenticated/production.recipe-categories'
import { Route as AuthenticatedProductionQcRouteImport } from './routes/_authenticated/production.qc'
import { Route as AuthenticatedProductionCostReportRouteImport } from './routes/_authenticated/production.cost-report'
import { Route as AuthenticatedProductionConsumptionReportRouteImport } from './routes/_authenticated/production.consumption-report'
import { Route as AuthenticatedProductionBatchesRouteImport } from './routes/_authenticated/production.batches'
import { Route as AuthenticatedExpensesReportRouteImport } from './routes/_authenticated/expenses.report'
import { Route as AuthenticatedExpensesNewRouteImport } from './routes/_authenticated/expenses.new'
import { Route as AuthenticatedExpensesListRouteImport } from './routes/_authenticated/expenses.list'
import { Route as AuthenticatedExpensesCategoriesRouteImport } from './routes/_authenticated/expenses.categories'
import { Route as AuthenticatedEmployeesNewRouteImport } from './routes/_authenticated/employees.new'
import { Route as AuthenticatedCrmIdRouteImport } from './routes/_authenticated/crm.$id'
import { Route as AuthenticatedTransfersDamagedNewRouteImport } from './routes/_authenticated/transfers.damaged.new'
import { Route as AuthenticatedSalesEditIdRouteImport } from './routes/_authenticated/sales.edit.$id'
import { Route as AuthenticatedProductsEditIdRouteImport } from './routes/_authenticated/products.edit.$id'
import { Route as AuthenticatedEmployeesEditIdRouteImport } from './routes/_authenticated/employees.edit.$id'
import { Route as AuthenticatedCrmIdLedgerRouteImport } from './routes/_authenticated/crm.$id.ledger'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRawMaterialsRoute =
  AuthenticatedRawMaterialsRouteImport.update({
    id: '/raw-materials',
    path: '/raw-materials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRawMaterialStockRoute =
  AuthenticatedRawMaterialStockRouteImport.update({
    id: '/raw-material-stock',
    path: '/raw-material-stock',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductStockRoute =
  AuthenticatedProductStockRouteImport.update({
    id: '/product-stock',
    path: '/product-stock',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomerGroupsRoute =
  AuthenticatedCustomerGroupsRouteImport.update({
    id: '/customer-groups',
    path: '/customer-groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiInsightsRoute = AuthenticatedAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersIndexRoute =
  AuthenticatedTransfersIndexRouteImport.update({
    id: '/transfers/',
    path: '/transfers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionIndexRoute =
  AuthenticatedProductionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const ApiPublicSupabaseProxyRoute = ApiPublicSupabaseProxyRouteImport.update({
  id: '/api/public/supabase-proxy',
  path: '/api/public/supabase-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransfersNewRoute =
  AuthenticatedTransfersNewRouteImport.update({
    id: '/transfers/new',
    path: '/transfers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsShowroomsRoute =
  AuthenticatedSettingsShowroomsRouteImport.update({
    id: '/settings/showrooms',
    path: '/settings/showrooms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsLandingRoute =
  AuthenticatedSettingsLandingRouteImport.update({
    id: '/settings/landing',
    path: '/settings/landing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAccessRoute =
  AuthenticatedSettingsAccessRouteImport.update({
    id: '/settings/access',
    path: '/settings/access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesReturnRoute =
  AuthenticatedSalesReturnRouteImport.update({
    id: '/sales/return',
    path: '/sales/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesPaymentsRoute =
  AuthenticatedSalesPaymentsRouteImport.update({
    id: '/sales/payments',
    path: '/sales/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesListRoute = AuthenticatedSalesListRouteImport.update({
  id: '/sales/list',
  path: '/sales/list',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesHistoryRoute =
  AuthenticatedSalesHistoryRouteImport.update({
    id: '/sales/history',
    path: '/sales/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsStockRoute =
  AuthenticatedReportsStockRouteImport.update({
    id: '/stock',
    path: '/stock',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsSalesRoute =
  AuthenticatedReportsSalesRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsPurchaseRoute =
  AuthenticatedReportsPurchaseRouteImport.update({
    id: '/purchase',
    path: '/purchase',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsLedgersRoute =
  AuthenticatedReportsLedgersRouteImport.update({
    id: '/ledgers',
    path: '/ledgers',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsExpensesRoute =
  AuthenticatedReportsExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedPurchasingReturnsRoute =
  AuthenticatedPurchasingReturnsRouteImport.update({
    id: '/purchasing/returns',
    path: '/purchasing/returns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingPaymentsRoute =
  AuthenticatedPurchasingPaymentsRouteImport.update({
    id: '/purchasing/payments',
    path: '/purchasing/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingNewRoute =
  AuthenticatedPurchasingNewRouteImport.update({
    id: '/purchasing/new',
    path: '/purchasing/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingListRoute =
  AuthenticatedPurchasingListRouteImport.update({
    id: '/purchasing/list',
    path: '/purchasing/list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingCategoriesRoute =
  AuthenticatedPurchasingCategoriesRouteImport.update({
    id: '/purchasing/categories',
    path: '/purchasing/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsUnitsRoute =
  AuthenticatedProductsUnitsRouteImport.update({
    id: '/products/units',
    path: '/products/units',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsSellingPriceGroupsRoute =
  AuthenticatedProductsSellingPriceGroupsRouteImport.update({
    id: '/products/selling-price-groups',
    path: '/products/selling-price-groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsCategoriesRoute =
  AuthenticatedProductsCategoriesRouteImport.update({
    id: '/products/categories',
    path: '/products/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionWorkOrdersRoute =
  AuthenticatedProductionWorkOrdersRouteImport.update({
    id: '/work-orders',
    path: '/work-orders',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionWastageRoute =
  AuthenticatedProductionWastageRouteImport.update({
    id: '/wastage',
    path: '/wastage',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionRepurposeRoute =
  AuthenticatedProductionRepurposeRouteImport.update({
    id: '/repurpose',
    path: '/repurpose',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionRecipeCategoriesRoute =
  AuthenticatedProductionRecipeCategoriesRouteImport.update({
    id: '/recipe-categories',
    path: '/recipe-categories',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionQcRoute =
  AuthenticatedProductionQcRouteImport.update({
    id: '/qc',
    path: '/qc',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionCostReportRoute =
  AuthenticatedProductionCostReportRouteImport.update({
    id: '/cost-report',
    path: '/cost-report',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionConsumptionReportRoute =
  AuthenticatedProductionConsumptionReportRouteImport.update({
    id: '/consumption-report',
    path: '/consumption-report',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductionBatchesRoute =
  AuthenticatedProductionBatchesRouteImport.update({
    id: '/batches',
    path: '/batches',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedExpensesReportRoute =
  AuthenticatedExpensesReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedExpensesRoute,
  } as any)
const AuthenticatedExpensesNewRoute =
  AuthenticatedExpensesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedExpensesRoute,
  } as any)
const AuthenticatedExpensesListRoute =
  AuthenticatedExpensesListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AuthenticatedExpensesRoute,
  } as any)
const AuthenticatedExpensesCategoriesRoute =
  AuthenticatedExpensesCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedExpensesRoute,
  } as any)
const AuthenticatedEmployeesNewRoute =
  AuthenticatedEmployeesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedEmployeesRoute,
  } as any)
const AuthenticatedCrmIdRoute = AuthenticatedCrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedTransfersDamagedNewRoute =
  AuthenticatedTransfersDamagedNewRouteImport.update({
    id: '/transfers/damaged/new',
    path: '/transfers/damaged/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesEditIdRoute =
  AuthenticatedSalesEditIdRouteImport.update({
    id: '/sales/edit/$id',
    path: '/sales/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsEditIdRoute =
  AuthenticatedProductsEditIdRouteImport.update({
    id: '/products/edit/$id',
    path: '/products/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesEditIdRoute =
  AuthenticatedEmployeesEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedEmployeesRoute,
  } as any)
const AuthenticatedCrmIdLedgerRoute =
  AuthenticatedCrmIdLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => AuthenticatedCrmIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounting': typeof AuthenticatedAccountingRoute
  '/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/customer-groups': typeof AuthenticatedCustomerGroupsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/expenses': typeof AuthenticatedExpensesRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pos': typeof AuthenticatedPosRoute
  '/product-stock': typeof AuthenticatedProductStockRoute
  '/production': typeof AuthenticatedProductionRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/raw-material-stock': typeof AuthenticatedRawMaterialStockRoute
  '/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/crm/$id': typeof AuthenticatedCrmIdRouteWithChildren
  '/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/expenses/categories': typeof AuthenticatedExpensesCategoriesRoute
  '/expenses/list': typeof AuthenticatedExpensesListRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/expenses/report': typeof AuthenticatedExpensesReportRoute
  '/production/batches': typeof AuthenticatedProductionBatchesRoute
  '/production/consumption-report': typeof AuthenticatedProductionConsumptionReportRoute
  '/production/cost-report': typeof AuthenticatedProductionCostReportRoute
  '/production/qc': typeof AuthenticatedProductionQcRoute
  '/production/recipe-categories': typeof AuthenticatedProductionRecipeCategoriesRoute
  '/production/repurpose': typeof AuthenticatedProductionRepurposeRoute
  '/production/wastage': typeof AuthenticatedProductionWastageRoute
  '/production/work-orders': typeof AuthenticatedProductionWorkOrdersRoute
  '/products/categories': typeof AuthenticatedProductsCategoriesRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/products/selling-price-groups': typeof AuthenticatedProductsSellingPriceGroupsRoute
  '/products/units': typeof AuthenticatedProductsUnitsRoute
  '/purchasing/categories': typeof AuthenticatedPurchasingCategoriesRoute
  '/purchasing/list': typeof AuthenticatedPurchasingListRoute
  '/purchasing/new': typeof AuthenticatedPurchasingNewRoute
  '/purchasing/payments': typeof AuthenticatedPurchasingPaymentsRoute
  '/purchasing/returns': typeof AuthenticatedPurchasingReturnsRoute
  '/reports/expenses': typeof AuthenticatedReportsExpensesRoute
  '/reports/ledgers': typeof AuthenticatedReportsLedgersRoute
  '/reports/purchase': typeof AuthenticatedReportsPurchaseRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/reports/stock': typeof AuthenticatedReportsStockRoute
  '/sales/history': typeof AuthenticatedSalesHistoryRoute
  '/sales/list': typeof AuthenticatedSalesListRoute
  '/sales/payments': typeof AuthenticatedSalesPaymentsRoute
  '/sales/return': typeof AuthenticatedSalesReturnRoute
  '/settings/access': typeof AuthenticatedSettingsAccessRoute
  '/settings/landing': typeof AuthenticatedSettingsLandingRoute
  '/settings/showrooms': typeof AuthenticatedSettingsShowroomsRoute
  '/transfers/new': typeof AuthenticatedTransfersNewRoute
  '/api/public/supabase-proxy': typeof ApiPublicSupabaseProxyRoute
  '/production/': typeof AuthenticatedProductionIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/transfers/': typeof AuthenticatedTransfersIndexRoute
  '/crm/$id/ledger': typeof AuthenticatedCrmIdLedgerRoute
  '/employees/edit/$id': typeof AuthenticatedEmployeesEditIdRoute
  '/products/edit/$id': typeof AuthenticatedProductsEditIdRoute
  '/sales/edit/$id': typeof AuthenticatedSalesEditIdRoute
  '/transfers/damaged/new': typeof AuthenticatedTransfersDamagedNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounting': typeof AuthenticatedAccountingRoute
  '/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/customer-groups': typeof AuthenticatedCustomerGroupsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/expenses': typeof AuthenticatedExpensesRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pos': typeof AuthenticatedPosRoute
  '/product-stock': typeof AuthenticatedProductStockRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/raw-material-stock': typeof AuthenticatedRawMaterialStockRoute
  '/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/crm/$id': typeof AuthenticatedCrmIdRouteWithChildren
  '/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/expenses/categories': typeof AuthenticatedExpensesCategoriesRoute
  '/expenses/list': typeof AuthenticatedExpensesListRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/expenses/report': typeof AuthenticatedExpensesReportRoute
  '/production/batches': typeof AuthenticatedProductionBatchesRoute
  '/production/consumption-report': typeof AuthenticatedProductionConsumptionReportRoute
  '/production/cost-report': typeof AuthenticatedProductionCostReportRoute
  '/production/qc': typeof AuthenticatedProductionQcRoute
  '/production/recipe-categories': typeof AuthenticatedProductionRecipeCategoriesRoute
  '/production/repurpose': typeof AuthenticatedProductionRepurposeRoute
  '/production/wastage': typeof AuthenticatedProductionWastageRoute
  '/production/work-orders': typeof AuthenticatedProductionWorkOrdersRoute
  '/products/categories': typeof AuthenticatedProductsCategoriesRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/products/selling-price-groups': typeof AuthenticatedProductsSellingPriceGroupsRoute
  '/products/units': typeof AuthenticatedProductsUnitsRoute
  '/purchasing/categories': typeof AuthenticatedPurchasingCategoriesRoute
  '/purchasing/list': typeof AuthenticatedPurchasingListRoute
  '/purchasing/new': typeof AuthenticatedPurchasingNewRoute
  '/purchasing/payments': typeof AuthenticatedPurchasingPaymentsRoute
  '/purchasing/returns': typeof AuthenticatedPurchasingReturnsRoute
  '/reports/expenses': typeof AuthenticatedReportsExpensesRoute
  '/reports/ledgers': typeof AuthenticatedReportsLedgersRoute
  '/reports/purchase': typeof AuthenticatedReportsPurchaseRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/reports/stock': typeof AuthenticatedReportsStockRoute
  '/sales/history': typeof AuthenticatedSalesHistoryRoute
  '/sales/list': typeof AuthenticatedSalesListRoute
  '/sales/payments': typeof AuthenticatedSalesPaymentsRoute
  '/sales/return': typeof AuthenticatedSalesReturnRoute
  '/settings/access': typeof AuthenticatedSettingsAccessRoute
  '/settings/landing': typeof AuthenticatedSettingsLandingRoute
  '/settings/showrooms': typeof AuthenticatedSettingsShowroomsRoute
  '/transfers/new': typeof AuthenticatedTransfersNewRoute
  '/api/public/supabase-proxy': typeof ApiPublicSupabaseProxyRoute
  '/production': typeof AuthenticatedProductionIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/transfers': typeof AuthenticatedTransfersIndexRoute
  '/crm/$id/ledger': typeof AuthenticatedCrmIdLedgerRoute
  '/employees/edit/$id': typeof AuthenticatedEmployeesEditIdRoute
  '/products/edit/$id': typeof AuthenticatedProductsEditIdRoute
  '/sales/edit/$id': typeof AuthenticatedSalesEditIdRoute
  '/transfers/damaged/new': typeof AuthenticatedTransfersDamagedNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/accounting': typeof AuthenticatedAccountingRoute
  '/_authenticated/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/customer-groups': typeof AuthenticatedCustomerGroupsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/_authenticated/expenses': typeof AuthenticatedExpensesRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/product-stock': typeof AuthenticatedProductStockRoute
  '/_authenticated/production': typeof AuthenticatedProductionRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/raw-material-stock': typeof AuthenticatedRawMaterialStockRoute
  '/_authenticated/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/_authenticated/crm/$id': typeof AuthenticatedCrmIdRouteWithChildren
  '/_authenticated/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/_authenticated/expenses/categories': typeof AuthenticatedExpensesCategoriesRoute
  '/_authenticated/expenses/list': typeof AuthenticatedExpensesListRoute
  '/_authenticated/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/_authenticated/expenses/report': typeof AuthenticatedExpensesReportRoute
  '/_authenticated/production/batches': typeof AuthenticatedProductionBatchesRoute
  '/_authenticated/production/consumption-report': typeof AuthenticatedProductionConsumptionReportRoute
  '/_authenticated/production/cost-report': typeof AuthenticatedProductionCostReportRoute
  '/_authenticated/production/qc': typeof AuthenticatedProductionQcRoute
  '/_authenticated/production/recipe-categories': typeof AuthenticatedProductionRecipeCategoriesRoute
  '/_authenticated/production/repurpose': typeof AuthenticatedProductionRepurposeRoute
  '/_authenticated/production/wastage': typeof AuthenticatedProductionWastageRoute
  '/_authenticated/production/work-orders': typeof AuthenticatedProductionWorkOrdersRoute
  '/_authenticated/products/categories': typeof AuthenticatedProductsCategoriesRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/products/selling-price-groups': typeof AuthenticatedProductsSellingPriceGroupsRoute
  '/_authenticated/products/units': typeof AuthenticatedProductsUnitsRoute
  '/_authenticated/purchasing/categories': typeof AuthenticatedPurchasingCategoriesRoute
  '/_authenticated/purchasing/list': typeof AuthenticatedPurchasingListRoute
  '/_authenticated/purchasing/new': typeof AuthenticatedPurchasingNewRoute
  '/_authenticated/purchasing/payments': typeof AuthenticatedPurchasingPaymentsRoute
  '/_authenticated/purchasing/returns': typeof AuthenticatedPurchasingReturnsRoute
  '/_authenticated/reports/expenses': typeof AuthenticatedReportsExpensesRoute
  '/_authenticated/reports/ledgers': typeof AuthenticatedReportsLedgersRoute
  '/_authenticated/reports/purchase': typeof AuthenticatedReportsPurchaseRoute
  '/_authenticated/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/_authenticated/reports/stock': typeof AuthenticatedReportsStockRoute
  '/_authenticated/sales/history': typeof AuthenticatedSalesHistoryRoute
  '/_authenticated/sales/list': typeof AuthenticatedSalesListRoute
  '/_authenticated/sales/payments': typeof AuthenticatedSalesPaymentsRoute
  '/_authenticated/sales/return': typeof AuthenticatedSalesReturnRoute
  '/_authenticated/settings/access': typeof AuthenticatedSettingsAccessRoute
  '/_authenticated/settings/landing': typeof AuthenticatedSettingsLandingRoute
  '/_authenticated/settings/showrooms': typeof AuthenticatedSettingsShowroomsRoute
  '/_authenticated/transfers/new': typeof AuthenticatedTransfersNewRoute
  '/api/public/supabase-proxy': typeof ApiPublicSupabaseProxyRoute
  '/_authenticated/production/': typeof AuthenticatedProductionIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/transfers/': typeof AuthenticatedTransfersIndexRoute
  '/_authenticated/crm/$id/ledger': typeof AuthenticatedCrmIdLedgerRoute
  '/_authenticated/employees/edit/$id': typeof AuthenticatedEmployeesEditIdRoute
  '/_authenticated/products/edit/$id': typeof AuthenticatedProductsEditIdRoute
  '/_authenticated/sales/edit/$id': typeof AuthenticatedSalesEditIdRoute
  '/_authenticated/transfers/damaged/new': typeof AuthenticatedTransfersDamagedNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/accounting'
    | '/ai-insights'
    | '/branches'
    | '/catalog'
    | '/crm'
    | '/customer-groups'
    | '/dashboard'
    | '/employees'
    | '/expenses'
    | '/inventory'
    | '/orders'
    | '/pos'
    | '/product-stock'
    | '/production'
    | '/profile'
    | '/raw-material-stock'
    | '/raw-materials'
    | '/recipes'
    | '/reports'
    | '/suppliers'
    | '/invoice/$id'
    | '/crm/$id'
    | '/employees/new'
    | '/expenses/categories'
    | '/expenses/list'
    | '/expenses/new'
    | '/expenses/report'
    | '/production/batches'
    | '/production/consumption-report'
    | '/production/cost-report'
    | '/production/qc'
    | '/production/recipe-categories'
    | '/production/repurpose'
    | '/production/wastage'
    | '/production/work-orders'
    | '/products/categories'
    | '/products/new'
    | '/products/selling-price-groups'
    | '/products/units'
    | '/purchasing/categories'
    | '/purchasing/list'
    | '/purchasing/new'
    | '/purchasing/payments'
    | '/purchasing/returns'
    | '/reports/expenses'
    | '/reports/ledgers'
    | '/reports/purchase'
    | '/reports/sales'
    | '/reports/stock'
    | '/sales/history'
    | '/sales/list'
    | '/sales/payments'
    | '/sales/return'
    | '/settings/access'
    | '/settings/landing'
    | '/settings/showrooms'
    | '/transfers/new'
    | '/api/public/supabase-proxy'
    | '/production/'
    | '/products/'
    | '/reports/'
    | '/settings/'
    | '/transfers/'
    | '/crm/$id/ledger'
    | '/employees/edit/$id'
    | '/products/edit/$id'
    | '/sales/edit/$id'
    | '/transfers/damaged/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/accounting'
    | '/ai-insights'
    | '/branches'
    | '/catalog'
    | '/crm'
    | '/customer-groups'
    | '/dashboard'
    | '/employees'
    | '/expenses'
    | '/inventory'
    | '/orders'
    | '/pos'
    | '/product-stock'
    | '/profile'
    | '/raw-material-stock'
    | '/raw-materials'
    | '/recipes'
    | '/suppliers'
    | '/invoice/$id'
    | '/crm/$id'
    | '/employees/new'
    | '/expenses/categories'
    | '/expenses/list'
    | '/expenses/new'
    | '/expenses/report'
    | '/production/batches'
    | '/production/consumption-report'
    | '/production/cost-report'
    | '/production/qc'
    | '/production/recipe-categories'
    | '/production/repurpose'
    | '/production/wastage'
    | '/production/work-orders'
    | '/products/categories'
    | '/products/new'
    | '/products/selling-price-groups'
    | '/products/units'
    | '/purchasing/categories'
    | '/purchasing/list'
    | '/purchasing/new'
    | '/purchasing/payments'
    | '/purchasing/returns'
    | '/reports/expenses'
    | '/reports/ledgers'
    | '/reports/purchase'
    | '/reports/sales'
    | '/reports/stock'
    | '/sales/history'
    | '/sales/list'
    | '/sales/payments'
    | '/sales/return'
    | '/settings/access'
    | '/settings/landing'
    | '/settings/showrooms'
    | '/transfers/new'
    | '/api/public/supabase-proxy'
    | '/production'
    | '/products'
    | '/reports'
    | '/settings'
    | '/transfers'
    | '/crm/$id/ledger'
    | '/employees/edit/$id'
    | '/products/edit/$id'
    | '/sales/edit/$id'
    | '/transfers/damaged/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/accounting'
    | '/_authenticated/ai-insights'
    | '/_authenticated/branches'
    | '/_authenticated/catalog'
    | '/_authenticated/crm'
    | '/_authenticated/customer-groups'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/expenses'
    | '/_authenticated/inventory'
    | '/_authenticated/orders'
    | '/_authenticated/pos'
    | '/_authenticated/product-stock'
    | '/_authenticated/production'
    | '/_authenticated/profile'
    | '/_authenticated/raw-material-stock'
    | '/_authenticated/raw-materials'
    | '/_authenticated/recipes'
    | '/_authenticated/reports'
    | '/_authenticated/suppliers'
    | '/invoice/$id'
    | '/_authenticated/crm/$id'
    | '/_authenticated/employees/new'
    | '/_authenticated/expenses/categories'
    | '/_authenticated/expenses/list'
    | '/_authenticated/expenses/new'
    | '/_authenticated/expenses/report'
    | '/_authenticated/production/batches'
    | '/_authenticated/production/consumption-report'
    | '/_authenticated/production/cost-report'
    | '/_authenticated/production/qc'
    | '/_authenticated/production/recipe-categories'
    | '/_authenticated/production/repurpose'
    | '/_authenticated/production/wastage'
    | '/_authenticated/production/work-orders'
    | '/_authenticated/products/categories'
    | '/_authenticated/products/new'
    | '/_authenticated/products/selling-price-groups'
    | '/_authenticated/products/units'
    | '/_authenticated/purchasing/categories'
    | '/_authenticated/purchasing/list'
    | '/_authenticated/purchasing/new'
    | '/_authenticated/purchasing/payments'
    | '/_authenticated/purchasing/returns'
    | '/_authenticated/reports/expenses'
    | '/_authenticated/reports/ledgers'
    | '/_authenticated/reports/purchase'
    | '/_authenticated/reports/sales'
    | '/_authenticated/reports/stock'
    | '/_authenticated/sales/history'
    | '/_authenticated/sales/list'
    | '/_authenticated/sales/payments'
    | '/_authenticated/sales/return'
    | '/_authenticated/settings/access'
    | '/_authenticated/settings/landing'
    | '/_authenticated/settings/showrooms'
    | '/_authenticated/transfers/new'
    | '/api/public/supabase-proxy'
    | '/_authenticated/production/'
    | '/_authenticated/products/'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/_authenticated/transfers/'
    | '/_authenticated/crm/$id/ledger'
    | '/_authenticated/employees/edit/$id'
    | '/_authenticated/products/edit/$id'
    | '/_authenticated/sales/edit/$id'
    | '/_authenticated/transfers/damaged/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  ApiPublicSupabaseProxyRoute: typeof ApiPublicSupabaseProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/raw-materials': {
      id: '/_authenticated/raw-materials'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof AuthenticatedRawMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/raw-material-stock': {
      id: '/_authenticated/raw-material-stock'
      path: '/raw-material-stock'
      fullPath: '/raw-material-stock'
      preLoaderRoute: typeof AuthenticatedRawMaterialStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product-stock': {
      id: '/_authenticated/product-stock'
      path: '/product-stock'
      fullPath: '/product-stock'
      preLoaderRoute: typeof AuthenticatedProductStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer-groups': {
      id: '/_authenticated/customer-groups'
      path: '/customer-groups'
      fullPath: '/customer-groups'
      preLoaderRoute: typeof AuthenticatedCustomerGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-insights': {
      id: '/_authenticated/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AuthenticatedAiInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting': {
      id: '/_authenticated/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers/': {
      id: '/_authenticated/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof AuthenticatedTransfersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/': {
      id: '/_authenticated/production/'
      path: '/'
      fullPath: '/production/'
      preLoaderRoute: typeof AuthenticatedProductionIndexRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/api/public/supabase-proxy': {
      id: '/api/public/supabase-proxy'
      path: '/api/public/supabase-proxy'
      fullPath: '/api/public/supabase-proxy'
      preLoaderRoute: typeof ApiPublicSupabaseProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transfers/new': {
      id: '/_authenticated/transfers/new'
      path: '/transfers/new'
      fullPath: '/transfers/new'
      preLoaderRoute: typeof AuthenticatedTransfersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/showrooms': {
      id: '/_authenticated/settings/showrooms'
      path: '/settings/showrooms'
      fullPath: '/settings/showrooms'
      preLoaderRoute: typeof AuthenticatedSettingsShowroomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/landing': {
      id: '/_authenticated/settings/landing'
      path: '/settings/landing'
      fullPath: '/settings/landing'
      preLoaderRoute: typeof AuthenticatedSettingsLandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/access': {
      id: '/_authenticated/settings/access'
      path: '/settings/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof AuthenticatedSettingsAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/return': {
      id: '/_authenticated/sales/return'
      path: '/sales/return'
      fullPath: '/sales/return'
      preLoaderRoute: typeof AuthenticatedSalesReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/payments': {
      id: '/_authenticated/sales/payments'
      path: '/sales/payments'
      fullPath: '/sales/payments'
      preLoaderRoute: typeof AuthenticatedSalesPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/list': {
      id: '/_authenticated/sales/list'
      path: '/sales/list'
      fullPath: '/sales/list'
      preLoaderRoute: typeof AuthenticatedSalesListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/history': {
      id: '/_authenticated/sales/history'
      path: '/sales/history'
      fullPath: '/sales/history'
      preLoaderRoute: typeof AuthenticatedSalesHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/stock': {
      id: '/_authenticated/reports/stock'
      path: '/stock'
      fullPath: '/reports/stock'
      preLoaderRoute: typeof AuthenticatedReportsStockRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/sales': {
      id: '/_authenticated/reports/sales'
      path: '/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AuthenticatedReportsSalesRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/purchase': {
      id: '/_authenticated/reports/purchase'
      path: '/purchase'
      fullPath: '/reports/purchase'
      preLoaderRoute: typeof AuthenticatedReportsPurchaseRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/ledgers': {
      id: '/_authenticated/reports/ledgers'
      path: '/ledgers'
      fullPath: '/reports/ledgers'
      preLoaderRoute: typeof AuthenticatedReportsLedgersRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/expenses': {
      id: '/_authenticated/reports/expenses'
      path: '/expenses'
      fullPath: '/reports/expenses'
      preLoaderRoute: typeof AuthenticatedReportsExpensesRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/purchasing/returns': {
      id: '/_authenticated/purchasing/returns'
      path: '/purchasing/returns'
      fullPath: '/purchasing/returns'
      preLoaderRoute: typeof AuthenticatedPurchasingReturnsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/payments': {
      id: '/_authenticated/purchasing/payments'
      path: '/purchasing/payments'
      fullPath: '/purchasing/payments'
      preLoaderRoute: typeof AuthenticatedPurchasingPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/new': {
      id: '/_authenticated/purchasing/new'
      path: '/purchasing/new'
      fullPath: '/purchasing/new'
      preLoaderRoute: typeof AuthenticatedPurchasingNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/list': {
      id: '/_authenticated/purchasing/list'
      path: '/purchasing/list'
      fullPath: '/purchasing/list'
      preLoaderRoute: typeof AuthenticatedPurchasingListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/categories': {
      id: '/_authenticated/purchasing/categories'
      path: '/purchasing/categories'
      fullPath: '/purchasing/categories'
      preLoaderRoute: typeof AuthenticatedPurchasingCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/units': {
      id: '/_authenticated/products/units'
      path: '/products/units'
      fullPath: '/products/units'
      preLoaderRoute: typeof AuthenticatedProductsUnitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/selling-price-groups': {
      id: '/_authenticated/products/selling-price-groups'
      path: '/products/selling-price-groups'
      fullPath: '/products/selling-price-groups'
      preLoaderRoute: typeof AuthenticatedProductsSellingPriceGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/categories': {
      id: '/_authenticated/products/categories'
      path: '/products/categories'
      fullPath: '/products/categories'
      preLoaderRoute: typeof AuthenticatedProductsCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/work-orders': {
      id: '/_authenticated/production/work-orders'
      path: '/work-orders'
      fullPath: '/production/work-orders'
      preLoaderRoute: typeof AuthenticatedProductionWorkOrdersRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/wastage': {
      id: '/_authenticated/production/wastage'
      path: '/wastage'
      fullPath: '/production/wastage'
      preLoaderRoute: typeof AuthenticatedProductionWastageRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/repurpose': {
      id: '/_authenticated/production/repurpose'
      path: '/repurpose'
      fullPath: '/production/repurpose'
      preLoaderRoute: typeof AuthenticatedProductionRepurposeRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/recipe-categories': {
      id: '/_authenticated/production/recipe-categories'
      path: '/recipe-categories'
      fullPath: '/production/recipe-categories'
      preLoaderRoute: typeof AuthenticatedProductionRecipeCategoriesRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/qc': {
      id: '/_authenticated/production/qc'
      path: '/qc'
      fullPath: '/production/qc'
      preLoaderRoute: typeof AuthenticatedProductionQcRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/cost-report': {
      id: '/_authenticated/production/cost-report'
      path: '/cost-report'
      fullPath: '/production/cost-report'
      preLoaderRoute: typeof AuthenticatedProductionCostReportRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/consumption-report': {
      id: '/_authenticated/production/consumption-report'
      path: '/consumption-report'
      fullPath: '/production/consumption-report'
      preLoaderRoute: typeof AuthenticatedProductionConsumptionReportRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/production/batches': {
      id: '/_authenticated/production/batches'
      path: '/batches'
      fullPath: '/production/batches'
      preLoaderRoute: typeof AuthenticatedProductionBatchesRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/expenses/report': {
      id: '/_authenticated/expenses/report'
      path: '/report'
      fullPath: '/expenses/report'
      preLoaderRoute: typeof AuthenticatedExpensesReportRouteImport
      parentRoute: typeof AuthenticatedExpensesRoute
    }
    '/_authenticated/expenses/new': {
      id: '/_authenticated/expenses/new'
      path: '/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AuthenticatedExpensesNewRouteImport
      parentRoute: typeof AuthenticatedExpensesRoute
    }
    '/_authenticated/expenses/list': {
      id: '/_authenticated/expenses/list'
      path: '/list'
      fullPath: '/expenses/list'
      preLoaderRoute: typeof AuthenticatedExpensesListRouteImport
      parentRoute: typeof AuthenticatedExpensesRoute
    }
    '/_authenticated/expenses/categories': {
      id: '/_authenticated/expenses/categories'
      path: '/categories'
      fullPath: '/expenses/categories'
      preLoaderRoute: typeof AuthenticatedExpensesCategoriesRouteImport
      parentRoute: typeof AuthenticatedExpensesRoute
    }
    '/_authenticated/employees/new': {
      id: '/_authenticated/employees/new'
      path: '/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AuthenticatedEmployeesNewRouteImport
      parentRoute: typeof AuthenticatedEmployeesRoute
    }
    '/_authenticated/crm/$id': {
      id: '/_authenticated/crm/$id'
      path: '/$id'
      fullPath: '/crm/$id'
      preLoaderRoute: typeof AuthenticatedCrmIdRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/transfers/damaged/new': {
      id: '/_authenticated/transfers/damaged/new'
      path: '/transfers/damaged/new'
      fullPath: '/transfers/damaged/new'
      preLoaderRoute: typeof AuthenticatedTransfersDamagedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/edit/$id': {
      id: '/_authenticated/sales/edit/$id'
      path: '/sales/edit/$id'
      fullPath: '/sales/edit/$id'
      preLoaderRoute: typeof AuthenticatedSalesEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/edit/$id': {
      id: '/_authenticated/products/edit/$id'
      path: '/products/edit/$id'
      fullPath: '/products/edit/$id'
      preLoaderRoute: typeof AuthenticatedProductsEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees/edit/$id': {
      id: '/_authenticated/employees/edit/$id'
      path: '/edit/$id'
      fullPath: '/employees/edit/$id'
      preLoaderRoute: typeof AuthenticatedEmployeesEditIdRouteImport
      parentRoute: typeof AuthenticatedEmployeesRoute
    }
    '/_authenticated/crm/$id/ledger': {
      id: '/_authenticated/crm/$id/ledger'
      path: '/ledger'
      fullPath: '/crm/$id/ledger'
      preLoaderRoute: typeof AuthenticatedCrmIdLedgerRouteImport
      parentRoute: typeof AuthenticatedCrmIdRoute
    }
  }
}

interface AuthenticatedCrmIdRouteChildren {
  AuthenticatedCrmIdLedgerRoute: typeof AuthenticatedCrmIdLedgerRoute
}

const AuthenticatedCrmIdRouteChildren: AuthenticatedCrmIdRouteChildren = {
  AuthenticatedCrmIdLedgerRoute: AuthenticatedCrmIdLedgerRoute,
}

const AuthenticatedCrmIdRouteWithChildren =
  AuthenticatedCrmIdRoute._addFileChildren(AuthenticatedCrmIdRouteChildren)

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmIdRoute: typeof AuthenticatedCrmIdRouteWithChildren
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmIdRoute: AuthenticatedCrmIdRouteWithChildren,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedEmployeesRouteChildren {
  AuthenticatedEmployeesNewRoute: typeof AuthenticatedEmployeesNewRoute
  AuthenticatedEmployeesEditIdRoute: typeof AuthenticatedEmployeesEditIdRoute
}

const AuthenticatedEmployeesRouteChildren: AuthenticatedEmployeesRouteChildren =
  {
    AuthenticatedEmployeesNewRoute: AuthenticatedEmployeesNewRoute,
    AuthenticatedEmployeesEditIdRoute: AuthenticatedEmployeesEditIdRoute,
  }

const AuthenticatedEmployeesRouteWithChildren =
  AuthenticatedEmployeesRoute._addFileChildren(
    AuthenticatedEmployeesRouteChildren,
  )

interface AuthenticatedExpensesRouteChildren {
  AuthenticatedExpensesCategoriesRoute: typeof AuthenticatedExpensesCategoriesRoute
  AuthenticatedExpensesListRoute: typeof AuthenticatedExpensesListRoute
  AuthenticatedExpensesNewRoute: typeof AuthenticatedExpensesNewRoute
  AuthenticatedExpensesReportRoute: typeof AuthenticatedExpensesReportRoute
}

const AuthenticatedExpensesRouteChildren: AuthenticatedExpensesRouteChildren = {
  AuthenticatedExpensesCategoriesRoute: AuthenticatedExpensesCategoriesRoute,
  AuthenticatedExpensesListRoute: AuthenticatedExpensesListRoute,
  AuthenticatedExpensesNewRoute: AuthenticatedExpensesNewRoute,
  AuthenticatedExpensesReportRoute: AuthenticatedExpensesReportRoute,
}

const AuthenticatedExpensesRouteWithChildren =
  AuthenticatedExpensesRoute._addFileChildren(
    AuthenticatedExpensesRouteChildren,
  )

interface AuthenticatedProductionRouteChildren {
  AuthenticatedProductionBatchesRoute: typeof AuthenticatedProductionBatchesRoute
  AuthenticatedProductionConsumptionReportRoute: typeof AuthenticatedProductionConsumptionReportRoute
  AuthenticatedProductionCostReportRoute: typeof AuthenticatedProductionCostReportRoute
  AuthenticatedProductionQcRoute: typeof AuthenticatedProductionQcRoute
  AuthenticatedProductionRecipeCategoriesRoute: typeof AuthenticatedProductionRecipeCategoriesRoute
  AuthenticatedProductionRepurposeRoute: typeof AuthenticatedProductionRepurposeRoute
  AuthenticatedProductionWastageRoute: typeof AuthenticatedProductionWastageRoute
  AuthenticatedProductionWorkOrdersRoute: typeof AuthenticatedProductionWorkOrdersRoute
  AuthenticatedProductionIndexRoute: typeof AuthenticatedProductionIndexRoute
}

const AuthenticatedProductionRouteChildren: AuthenticatedProductionRouteChildren =
  {
    AuthenticatedProductionBatchesRoute: AuthenticatedProductionBatchesRoute,
    AuthenticatedProductionConsumptionReportRoute:
      AuthenticatedProductionConsumptionReportRoute,
    AuthenticatedProductionCostReportRoute:
      AuthenticatedProductionCostReportRoute,
    AuthenticatedProductionQcRoute: AuthenticatedProductionQcRoute,
    AuthenticatedProductionRecipeCategoriesRoute:
      AuthenticatedProductionRecipeCategoriesRoute,
    AuthenticatedProductionRepurposeRoute:
      AuthenticatedProductionRepurposeRoute,
    AuthenticatedProductionWastageRoute: AuthenticatedProductionWastageRoute,
    AuthenticatedProductionWorkOrdersRoute:
      AuthenticatedProductionWorkOrdersRoute,
    AuthenticatedProductionIndexRoute: AuthenticatedProductionIndexRoute,
  }

const AuthenticatedProductionRouteWithChildren =
  AuthenticatedProductionRoute._addFileChildren(
    AuthenticatedProductionRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsExpensesRoute: typeof AuthenticatedReportsExpensesRoute
  AuthenticatedReportsLedgersRoute: typeof AuthenticatedReportsLedgersRoute
  AuthenticatedReportsPurchaseRoute: typeof AuthenticatedReportsPurchaseRoute
  AuthenticatedReportsSalesRoute: typeof AuthenticatedReportsSalesRoute
  AuthenticatedReportsStockRoute: typeof AuthenticatedReportsStockRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsExpensesRoute: AuthenticatedReportsExpensesRoute,
  AuthenticatedReportsLedgersRoute: AuthenticatedReportsLedgersRoute,
  AuthenticatedReportsPurchaseRoute: AuthenticatedReportsPurchaseRoute,
  AuthenticatedReportsSalesRoute: AuthenticatedReportsSalesRoute,
  AuthenticatedReportsStockRoute: AuthenticatedReportsStockRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRoute
  AuthenticatedAiInsightsRoute: typeof AuthenticatedAiInsightsRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedCustomerGroupsRoute: typeof AuthenticatedCustomerGroupsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRouteWithChildren
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedProductStockRoute: typeof AuthenticatedProductStockRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRawMaterialStockRoute: typeof AuthenticatedRawMaterialStockRoute
  AuthenticatedRawMaterialsRoute: typeof AuthenticatedRawMaterialsRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedProductsCategoriesRoute: typeof AuthenticatedProductsCategoriesRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProductsSellingPriceGroupsRoute: typeof AuthenticatedProductsSellingPriceGroupsRoute
  AuthenticatedProductsUnitsRoute: typeof AuthenticatedProductsUnitsRoute
  AuthenticatedPurchasingCategoriesRoute: typeof AuthenticatedPurchasingCategoriesRoute
  AuthenticatedPurchasingListRoute: typeof AuthenticatedPurchasingListRoute
  AuthenticatedPurchasingNewRoute: typeof AuthenticatedPurchasingNewRoute
  AuthenticatedPurchasingPaymentsRoute: typeof AuthenticatedPurchasingPaymentsRoute
  AuthenticatedPurchasingReturnsRoute: typeof AuthenticatedPurchasingReturnsRoute
  AuthenticatedSalesHistoryRoute: typeof AuthenticatedSalesHistoryRoute
  AuthenticatedSalesListRoute: typeof AuthenticatedSalesListRoute
  AuthenticatedSalesPaymentsRoute: typeof AuthenticatedSalesPaymentsRoute
  AuthenticatedSalesReturnRoute: typeof AuthenticatedSalesReturnRoute
  AuthenticatedSettingsAccessRoute: typeof AuthenticatedSettingsAccessRoute
  AuthenticatedSettingsLandingRoute: typeof AuthenticatedSettingsLandingRoute
  AuthenticatedSettingsShowroomsRoute: typeof AuthenticatedSettingsShowroomsRoute
  AuthenticatedTransfersNewRoute: typeof AuthenticatedTransfersNewRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTransfersIndexRoute: typeof AuthenticatedTransfersIndexRoute
  AuthenticatedProductsEditIdRoute: typeof AuthenticatedProductsEditIdRoute
  AuthenticatedSalesEditIdRoute: typeof AuthenticatedSalesEditIdRoute
  AuthenticatedTransfersDamagedNewRoute: typeof AuthenticatedTransfersDamagedNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRoute,
  AuthenticatedAiInsightsRoute: AuthenticatedAiInsightsRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedCustomerGroupsRoute: AuthenticatedCustomerGroupsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRouteWithChildren,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedProductStockRoute: AuthenticatedProductStockRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRawMaterialStockRoute: AuthenticatedRawMaterialStockRoute,
  AuthenticatedRawMaterialsRoute: AuthenticatedRawMaterialsRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedProductsCategoriesRoute: AuthenticatedProductsCategoriesRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedProductsSellingPriceGroupsRoute:
    AuthenticatedProductsSellingPriceGroupsRoute,
  AuthenticatedProductsUnitsRoute: AuthenticatedProductsUnitsRoute,
  AuthenticatedPurchasingCategoriesRoute:
    AuthenticatedPurchasingCategoriesRoute,
  AuthenticatedPurchasingListRoute: AuthenticatedPurchasingListRoute,
  AuthenticatedPurchasingNewRoute: AuthenticatedPurchasingNewRoute,
  AuthenticatedPurchasingPaymentsRoute: AuthenticatedPurchasingPaymentsRoute,
  AuthenticatedPurchasingReturnsRoute: AuthenticatedPurchasingReturnsRoute,
  AuthenticatedSalesHistoryRoute: AuthenticatedSalesHistoryRoute,
  AuthenticatedSalesListRoute: AuthenticatedSalesListRoute,
  AuthenticatedSalesPaymentsRoute: AuthenticatedSalesPaymentsRoute,
  AuthenticatedSalesReturnRoute: AuthenticatedSalesReturnRoute,
  AuthenticatedSettingsAccessRoute: AuthenticatedSettingsAccessRoute,
  AuthenticatedSettingsLandingRoute: AuthenticatedSettingsLandingRoute,
  AuthenticatedSettingsShowroomsRoute: AuthenticatedSettingsShowroomsRoute,
  AuthenticatedTransfersNewRoute: AuthenticatedTransfersNewRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTransfersIndexRoute: AuthenticatedTransfersIndexRoute,
  AuthenticatedProductsEditIdRoute: AuthenticatedProductsEditIdRoute,
  AuthenticatedSalesEditIdRoute: AuthenticatedSalesEditIdRoute,
  AuthenticatedTransfersDamagedNewRoute: AuthenticatedTransfersDamagedNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  ApiPublicSupabaseProxyRoute: ApiPublicSupabaseProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
